### PR TITLE
incorporating feedback

### PR DESCRIPTION
**Pull request by rub1e**
Updated with feedback received so far. I think it's important that we comment on this, amend it, and merge it with master asap so people don't end up commenting on outdated versions. Please also note we need to have a proper new draft before Monday 19th Oct as this is when we agreed we will present to the rest of FAC so they have a week to comment on it before it is voted on (or just accepted) at the biz meeting on Monday 26th Oct. (Correct me if I'm wrong on that point)

@msmichellegar @minaorangina I have tried to address the issue of tone, and specifically have changed the bits you pulled out in #20. I have tried to walk the line between being welcoming, but also being declarative, instructional, and objective as Mina suggested in comments on #18.  

Re CoC - I have added this into the rules but I think for now we should revert to the vaguer language of being welcoming as ~~I think~~ I can guarantee there will be much healthy debate before we can agree on a full CoC  

@des-des I have changed that point based on your comment  

@sofer I added something in about London Living Wage which is basically me deciding policy on the fly (but I think it tracks with previous policies) - do take a look.  

---

For my money, I don't think this should be softened at all. If it were up to me, I'd have it printed, signed, then laminated. I'd turn it into a FACocratic oath that all new students should recite every morning. I think that amid all the avocados and clapping, we need to make it aggressively clear that this is a business that quite literally cannot afford passengers. Nonetheless I have toned it down as much as I can, please do let me know what you think.

### CODE REVIEW

**Comment by msmichellegar** [comment]
Not loving the proposed aggression, but this is much better. I would still like to do my own review of the language this evening as per https://github.com/foundersandcoders/charter/pull/21, as I think even this version could be improved upon.

**Comment by iteles** [comment]
I think the real problem here is that we haven't defined what this is, or who it's for (for certain, so that everyone's on the same page). Is this terms and conditions? A charter? A contract? A suggestion? A code of conduct? A gentle prod? We need to answer the question of what the aim of this document is before we know what tone it should be written in and what the contents should include.

**Comment by msmichellegar** [comment]
Good point @iteles ^^

**Comment by rub1e** [comment]
@msmichellegar thank you for making the time to review it this evening

@iteles my understanding after issues like #10 #9 etc. was that we are now working towards nothing more or less ambitious than a set of conditions that people from FAC7 must agree to before being accepted onto the course (hence the need for swift action) - which is why I changed the title

It is definitely not a suggestion or a prod, and it's definitely not a wider FAC charter

I think the issue of a code of conduct is totally separate as it will apply to everyone, not just new students - which is why I only put that language in as a placeholder for future iterations after we've gone through the lengthy process of agreeing what it should contain

To help us keep to the agreed timelines, **does anyone disagree that we should produce a set of rules for new students to ensure they contribute to FAC's financial stability?**  

If people do, then I suggest we scrap this and discuss how to proceed at the biz meeting on Monday. If not, then I suggest this document should be viewed only in that light.

**Comment by iteles** [comment]
@rub1e I don't disagree Rubie. What I mean is that not everyone has the availability to read every long thread in every issue so the answer to the fundamental questions was hidden away. We were all making comments but not all using even vaguely similar assumptions.

**Comment by rub1e** [comment]
@iteles Massively agree, there have defo been many cross-purpose discussions along the way (i am v guilty of this) - would it be worth scrapping this repo and starting a new one with some explanatory text outlining what this is for, and then v3 for people to start commenting on?

**Comment by sofer** [comment]
@rub1e thank you so much for all your work on this. @msmichellegar thank you for taking the trouble to sort through the dross of my first draft and leave feedback. Very much looking forward to further input from you. Thank you also to @minaorangina for your comprehensive feedback. We also need to make sure that whatever we come up with fits with what @iteles and @nelsonic are planning for the A-Team.

**Comment by des-des** [comment]
I think this is much better all round. Also, the code of conduct link is broken: http://www.foundersandcoders.com/coc

**Comment by rub1e** [comment]
@des-des that was just a placeholder - we don't have a code and until we do I think we'll have to revert to the language that was about making people feel welcome in the space

**Comment by des-des** [comment]
ok cool that sound good

**Pull request merged**
